-- AlterTable
ALTER TABLE `emailvalidationtokens` MODIFY `expiresAt` DATETIME(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL 1 DAY);

-- AlterTable
ALTER TABLE `passwordresettokens` MODIFY `expiresAt` DATETIME(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL 5 MINUTE);

-- AlterTable
ALTER TABLE `quiz` MODIFY `image` VARCHAR(191) NULL;
